### ISSUE TITLE
Testing: Internal tests or API tests?

### ISSUE THREAD

**Issue by Gouthamve** [fabxc/tsdb#16]
We are currently testing the package within the package, i.e. for example: via `package tsdb` as opposed to `package tsdb_test`.

I have seen that usually testing the API as a "user" of the package works well in the initial stages. We can have `_internal_test.go` if we want to test internal functions. This will also give us a little more clarity into what to expose and what to not.

If you think this is a good approach, I will move the existing tests to be external.

Ref: 2'nd point in https://medium.com/@benbjohnson/structuring-tests-in-go-46ddee7a25c#.rf85iysgp

**Comment by fabxc** [comment]
I suppose there's some benefit if you go that route strictly. But once you want to test "just that one internal type", you are stuck and have to add a separate brunch of the "internal tests" you mentioned. At this point I can't really see the point anymore. Now you obviously have the need for both, but what's the reason for keeping them separated?
Saving the programmer from themselves maybe? If I really want to cheat myself when writing tests, I can still just stuff it into the internal test file. What about cases where my types have an unexported function reporting the high-level internal state, e.g. suppose I've an eventually consistent DB and want to do timeout-free testing using the internal `DB.converge()`. Should I have to make that exported because my test wants to validate something? Arguably, that could be really bad as it might a very expensive function and should not be called by actual package users.

Lastly, it makes a fair bit of our structure more rigid. At some point we might want to consider moving some things like compaction or WAL into their own packages. If we have now another set of internal and external test packages, any transition will become harder.

So while I see some point, I'm not sure it gives all that much benefit at this point, assuming that everyone writing tests is reasonably honest as to what kind of test they want to write. I'd consider it again once the repo stabilised further.

I also tend to disagree with the religious "all dependencies are bad" philosophy hinted in the article. For example, we are using the `pkg/errors` and `testify/require` packages – both solving the exact same problem we would literally rebuild 1:1 – just that we'd repeat all the bugs and API considerations they already encountered & fixed.

**Comment by Gouthamve** [comment]
Understood, thanks!
